theme = "dark_plus"

[editor]
line-number = "relative"
cursorline = true
bufferline = "always"
mouse = false
scrolloff = 10
completion-replace = true
rulers = [120]
color-modes = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "file-encoding", "file-line-ending", "file-type"]
right = ["diagnostics", "workspace-diagnostics", "selections", "position", "total-line-numbers"]
