[language-server.graphql]
command = "graphql-lsp"
args = ["server", "-m", "stream"]

[language-server.eslint]
command = "eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
validate = "on"
packageManager = "yarn"
useESLintClass = false
experimental = { useFlatConfig = false }
codeActionOnSave = { enabled = false, mode = "all" }
format = false
quiet = false
onIgnoredFiles = "off"
rulesCustomizations = []
run = "onType"
problems = { shortenToSingleLine = false }
nodePath = ""
workingDirectory = { mode = "location" }
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }

[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "graphql"
language-servers = [ "graphql" ]

[[language]]
name = "dockerfile"
file-types = ["Dockerfile", "dockerfile", "Containerfile", "containerfile", "Dockerfile.dev"]

[[language]]
name = "typescript"
language-servers = [ {name = "typescript-language-server", except-features = [ "format" ]}, {name = "eslint", except-features = [ "format" ]} ]

[[language]]
name = "tsx"
language-servers = [ {name = "typescript-language-server", except-features = [ "format" ]}, {name = "eslint", except-features = [ "format" ]} ]

[[language]]
name = "javascript"
language-servers = [ {name = "typescript-language-server", except-features = [ "format" ]}, {name = "eslint", except-features = [ "format" ]} ]

[[language]]
name = "jsx"
language-servers = [ {name = "typescript-language-server", except-features = [ "format" ]}, {name = "eslint", except-features = [ "format" ]} ]
