[[language]]
name = "graphql"
language-server = { command = "graphql-lsp", args = ["server", "-m", "stream"] }

[[language]]
name = "dockerfile"
file-types = ["Dockerfile", "dockerfile", "Containerfile", "containerfile", "Dockerfile.dev"]
